/*
 ex: set tabstop=4 shiftwidth=4 autoindent:
 +-------------------------------------------------------------------------+
 | Copyright (C) 2004-2026 The Cacti Group                                 |
 |                                                                         |
 | This program is free software; you can redistribute it and/or           |
 | modify it under the terms of the GNU Lesser General Public              |
 | License as published by the Free Software Foundation; either            |
 | version 2.1 of the License, or (at your option) any later version. 	   |
 |                                                                         |
 | This program is distributed in the hope that it will be useful,         |
 | but WITHOUT ANY WARRANTY; without even the implied warranty of          |
 | MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the           |
 | GNU Lesser General Public License for more details.                     |
 |                                                                         |
 | You should have received a copy of the GNU Lesser General Public        |
 | License along with this library; if not, write to the Free Software     |
 | Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA           |
 | 02110-1301, USA                                                         |
 |                                                                         |
 +-------------------------------------------------------------------------+
 | spine: a backend data gatherer for cacti                                |
 +-------------------------------------------------------------------------+
 | This poller would not have been possible without:                       |
 |   - Larry Adams (current development and enhancements)                  |
 |   - Rivo Nurges (rrd support, mysql poller cache, misc functions)       |
 |   - RTG (core poller code, pthreads, snmp, autoconf examples)           |
 |   - Brady Alleman/Doug Warner (threading ideas, implementation details) |
 +-------------------------------------------------------------------------+
 | - Cacti - http://www.cacti.net/                                         |
 +-------------------------------------------------------------------------+
*/

#include "common.h"
#include "spine.h"

/*! \fn char *php_cmd(const char *php_command, int php_process)
 *  \brief calls the script server and executes a script command
 *  \param php_command the formatted php script server command
 *  \param php_process the php script server process to call
 *
 *  This function is called directly by the spine poller when a script server
 *  request has been initiated for a host.  It will place the PHP Script Server
 *  command on it's output pipe and then wait the pre-defined timeout period for
 *  a response on the PHP Script Servers output pipe.
 *
 *  \return pointer to the string results.  Must be freed by the parent.
 *
 */
static char *php_undefined_result(void) {
	char *result = strdup("U");
	if (result == NULL) die("ERROR: Fatal malloc error: PHP undefined result!");
	return result;
}

static bool php_write_command(int fd, const char *command) {
	/* A closed child pipe is a recoverable transport failure. Block SIGPIPE
	 * only in this thread and consume only a signal generated by this write. */
	sigset_t blocked;
	sigset_t previous;
	sigset_t pending;
	sigemptyset(&blocked);
	sigaddset(&blocked, SIGPIPE);
	if (pthread_sigmask(SIG_BLOCK, &blocked, &previous) != 0) return false;
	bool had_pending = sigpending(&pending) == 0 && sigismember(&pending, SIGPIPE) == 1;
	size_t sent = 0;
	size_t length = strlen(command);
	int failure = 0;
	while (sent < length) {
		ssize_t bytes = write(fd, command + sent, length - sent);
		if (bytes < 0 && errno == EINTR) continue;
		if (bytes <= 0) {
			failure = bytes < 0 ? errno : EIO;
			break;
		}
		sent += (size_t)bytes;
	}
	if (failure == EPIPE && !had_pending && sigpending(&pending) == 0 && sigismember(&pending, SIGPIPE) == 1) {
		int signal_number;
		sigwait(&blocked, &signal_number);
	}
	pthread_sigmask(SIG_SETMASK, &previous, NULL);
	if (failure != 0) errno = failure;
	return sent == length;
}

char *php_cmd(const char *php_command, int php_process) {
	static const int process_locks[MAX_PHP_SERVERS] = {
		LOCK_PHP_PROC_0, LOCK_PHP_PROC_1, LOCK_PHP_PROC_2, LOCK_PHP_PROC_3,
		LOCK_PHP_PROC_4, LOCK_PHP_PROC_5, LOCK_PHP_PROC_6, LOCK_PHP_PROC_7,
		LOCK_PHP_PROC_8, LOCK_PHP_PROC_9, LOCK_PHP_PROC_10, LOCK_PHP_PROC_11,
		LOCK_PHP_PROC_12, LOCK_PHP_PROC_13, LOCK_PHP_PROC_14
	};
	assert(php_command != NULL);
	char command[BUFSIZE];
	/* A request occupies one protocol line, including CR-LF and its NUL. */
	if (strlen(php_command) > sizeof(command) - 3 || strpbrk(php_command, "\r\n") != NULL) {
		SPINE_LOG(("ERROR: SS[%i] Invalid PHP Script Server command framing or length", php_process));
		return php_undefined_result();
	}
	if (php_process < 0 || php_process >= set.php_servers || php_process >= MAX_PHP_SERVERS || php_processes == NULL) {
		SPINE_LOG(("ERROR: SS[%i] Invalid PHP Script Server process", php_process));
		return php_undefined_result();
	}
	spine_snprintf(command, sizeof(command), "%s\r\n", php_command);
	int lock = process_locks[php_process];
	thread_mutex_lock(lock);
	char *result = NULL;
	for (int retry = 0; retry < 3; retry++) {
		if (php_write_command(php_processes[php_process].php_write_fd, command)) {
			result = php_readpipe(php_process, command);
			if (result[0] == '\0') SET_UNDEFINED(result);
			break;
		}
		SPINE_LOG(("ERROR: SS[%i] PHP Script Server communications lost sending command. Restarting PHP Script Server", php_process));
		php_close(php_process);
		if (!php_init(php_process)) break;
	}
	thread_mutex_unlock(lock);
	return result != NULL ? result : php_undefined_result();
}

/*!  \fn in php_get_process()
 *  \brief returns the next php script server process to utilize
 *
 *  This very simple function simply returns the next PHP Script Server
 *  process id to poll using a round robin algorithm.
 *
 *  \return the integer number of the next script server to use
 *
 */
int php_get_process(void) {
	int i;

	thread_mutex_lock(LOCK_PHP);
	if (set.php_current_server >= set.php_servers) {
		set.php_current_server = 0;
	}
	i = set.php_current_server;
	set.php_current_server++;
	thread_mutex_unlock(LOCK_PHP);

	return i;
}

/*! \fn char *php_readpipe(int php_process, char *command)
 *  \brief read a line from a PHP Script Server process
 *  \param php_process the PHP Script Server process to obtain output from
 *
 *  This function will read the output pipe from the PHP Script Server process
 *  and return that string to the Spine thread requesting the output.  If for
 *  some reason the PHP Script Server process does not respond in time, it will
 *  be closed using the php_close function, then restarted.
 *
 *  \return a string pointer to the PHP Script Server response
 */

/* Apply one total deadline to the complete frame, including every short read
 * and interrupted wait. A readable prefix alone is not a complete response. */
enum php_response_status php_read_response(int fd, char *buffer, size_t capacity, int seconds) {
	if (fd < 0 || fd >= FD_SETSIZE || buffer == NULL || capacity < 2 || seconds < 0) return PHP_RESPONSE_ERROR;
	buffer[0] = '\0';
	size_t used = 0;
	double deadline = spine_monotonic_time() + seconds;
	while (used < capacity - 1) {
		int ready = spine_wait_readable(fd, deadline);
		if (ready == 0) return PHP_RESPONSE_TIMEOUT;
		if (ready < 0) return PHP_RESPONSE_ERROR;
		ssize_t received = read(fd, buffer + used, capacity - 1 - used);
		if (received < 0 && errno == EINTR) continue;
		if (received < 0) return PHP_RESPONSE_ERROR;
		if (received == 0) return PHP_RESPONSE_EOF;
		if ((size_t)received > capacity - 1 - used) return PHP_RESPONSE_ERROR;
		used += (size_t)received;
		buffer[used] = '\0';
		if (strchr(buffer, '\n') != NULL) return PHP_RESPONSE_OK;
	}
	return PHP_RESPONSE_TOO_LONG;
}

char *php_readpipe(int php_process, const char *command) {
	if (php_processes == NULL || php_process < 0 || php_process >= set.php_servers || php_process >= MAX_PHP_SERVERS) {
		return php_undefined_result();
	}
	char *result = malloc(RESULTS_BUFFER);
	if (result == NULL) die("ERROR: Fatal malloc error: php.c php_readpipe!");
	enum php_response_status status = php_read_response(php_processes[php_process].php_read_fd,
		result, RESULTS_BUFFER, set.script_timeout);
	if (status == PHP_RESPONSE_OK) {
		php_processes[php_process].php_state = PHP_READY;
		return result;
	}
	SET_UNDEFINED(result);
	php_processes[php_process].php_state = PHP_BUSY;
	SPINE_LOG(("WARNING: SS[%i] Script Server response failed (status %i) for Command[%s]", php_process, status, command));
	php_close(php_process);
	/* A failed startup must return to its caller, never recursively start. */
	if (strcmp(command, "INIT") != 0) php_init(php_process);
	return result;
}

/*! \fn int php_init(int php_process)
 *  \brief initialize either a specific PHP Script Server or all of them.
 *  \param php_process the process number to start or PHP_INIT
 *
 *  This function will either start an individual PHP Script Server process
 *  or all of them if the input parameter is the PHP_INIT constant.  The function
 *  will check the status of the process to verify that it is ready to process
 *  scripts as well.
 *
 *  \return TRUE if the PHP Script Server is know running or FALSE otherwise
 */
static void php_build_arguments(char **argv, char *poller_id, size_t capacity) {
	argv[0] = set.path_php;
	argv[1] = "-q";
	argv[2] = set.path_php_server;
	if (set.cacti_version <= 1222) {
		argv[3] = "spine";
		spine_snprintf(poller_id, capacity, "%d", set.poller_id);
		argv[4] = poller_id;
		argv[5] = NULL;
		return;
	}
	argv[3] = "--environ=spine";
	spine_snprintf(poller_id, capacity, "--poller=%d", set.poller_id);
	argv[4] = poller_id;
	argv[5] = NULL;
	if (set.poller_id > 1) {
		argv[5] = set.mode == REMOTE_ONLINE ? "--mode=online" : "--mode=offline";
		argv[6] = NULL;
	}
}

static pid_t php_fork_server(int process) {
	for (int attempt = 0; attempt < 4; attempt++) {
		pid_t pid = fork();
		if (pid >= 0) return pid;
		if (errno != EAGAIN && errno != ENOMEM) break;
		#ifndef SOLAR_THREAD
		spine_sleep_usec(50000);
		#endif
	}
	SPINE_LOG(("ERROR: SS[%i] Could not fork PHP Script Server: %s", process, strerror(errno)));
	return -1;
}

static bool php_start_process(int process) {
	int requests[2];
	int responses[2];
	char poller_id[TINY_BUFSIZE];
	char *argv[7];
	int cancel_state;
	php_build_arguments(argv, poller_id, sizeof(poller_id));
	if (pipe(requests) < 0) {
		SPINE_LOG(("ERROR: SS[%i] Could not allocate PHP request pipe", process));
		return FALSE;
	}
	if (pipe(responses) < 0) {
		close(requests[0]);
		close(requests[1]);
		SPINE_LOG(("ERROR: SS[%i] Could not allocate PHP response pipe", process));
		return FALSE;
	}
	pthread_setcancelstate(PTHREAD_CANCEL_DISABLE, &cancel_state);
	pid_t pid = php_fork_server(process);
	if (pid == 0) {
		if (dup2(requests[0], STDIN_FILENO) < 0 || dup2(responses[1], STDOUT_FILENO) < 0) _exit(127);
		int descriptors[] = {requests[0], requests[1], responses[0], responses[1]};
		for (size_t i = 0; i < sizeof(descriptors) / sizeof(descriptors[0]); i++) {
			if (descriptors[i] != STDIN_FILENO && descriptors[i] != STDOUT_FILENO) close(descriptors[i]);
		}
		execv(argv[0], argv);
		_exit(127);
	}
	close(requests[0]);
	close(responses[1]);
	if (pid < 0) {
		close(requests[1]);
		close(responses[0]);
		pthread_setcancelstate(cancel_state, NULL);
		return FALSE;
	}
	php_t *server = &php_processes[process];
	server->php_pid = pid;
	server->php_write_fd = requests[1];
	server->php_read_fd = responses[0];
	server->php_state = PHP_BUSY;
	pthread_setcancelstate(cancel_state, NULL);
	char *result = php_readpipe(process, "INIT");
	bool started = strstr(result, "Started") != NULL;
	if (started) {
		SPINE_LOG_DEBUG(("DEBUG: SS[%i] Confirmed PHP Script Server running using readfd[%i], writefd[%i]",
			process, server->php_read_fd, server->php_write_fd));
		server->php_state = PHP_READY;
	} else {
		SPINE_LOG(("ERROR: SS[%i] Script Server did not start properly return message was: '%s'", process, result));
		server->php_state = PHP_BUSY;
		php_close(process);
	}
	free(result);
	return started;
}

int php_init(int php_process) {
	if (php_processes == NULL || set.php_servers < 0 || set.php_servers > MAX_PHP_SERVERS) return FALSE;
	if (php_process != PHP_INIT) {
		if (php_process < 0 || php_process >= set.php_servers) return FALSE;
		return php_start_process(php_process);
	}
	for (int process = 0; process < set.php_servers; process++) {
		if (!php_start_process(process)) return FALSE;
	}
	return TRUE;
}

/*! \fn void php_close(int php_process)
 *  \brief close the php script server process
 *  \param php_process the process to close or PHP_INIT
 *
 *  This function will take an input parameter of either a specially coded
 *  PHP_INIT parameter or an integer stating the process number.  With that
 *  information is will close and/or terminate the child PHP Script Server
 *  process and then return to the calling function.
 *
 *  TODO: Make ending of the child process not be reliant on SIG_TERM in cases
 *  where the child process is hung for one reason or another.
 *
 */
void php_close(int php_process) {
	int i;
	int num_processes;

	if (php_process == PHP_INIT) {
		num_processes = set.php_servers;
	} else {
		num_processes = 1;
	}

	for(i = 0; i < num_processes; i++) {
		php_t *phpp;

		SPINE_LOG_DEBUG(("DEBUG: SS[%i] Script Server Shutdown Started", i));

		/* tell the script server to close */
		if (php_process == PHP_INIT) {
			phpp = &php_processes[i];
		} else {
			phpp = &php_processes[php_process];
		}

		/* If we still have a valid write pipe, tell PHP to close down
		 * by sending a "quit" message, then closing the input channel
		 * so it gets an EOF.
		 *
		 * Then we wait a moment before actually killing it to allow for
		 * a clean shutdown.
		 */
		if (phpp->php_write_fd >= 0) {
			static const char quit[] = "quit\r\n";

			php_write_command(phpp->php_write_fd, quit);
			close(phpp->php_write_fd);
			phpp->php_write_fd = -1;

			/* wait before killing php */
			#ifndef SOLAR_THREAD
			spine_sleep_usec(50000);			/* 50 msec */
			#endif
		}

		/* only try to kill the process if the PID looks valid.
		 * Trying to kill a negative number is bad news (it's
	 	 * a process group leader), and PID 1 is "init".
	  	 */
		if (phpp->php_pid > 1) {
			/* end the php script server process */
			kill(phpp->php_pid, SIGTERM);

			/* reset this PID variable? */
		}

		/* close file descriptors */
		close(phpp->php_read_fd);
		phpp->php_read_fd  = -1;
	}
}
