# CMake generated Testfile for 
# Source directory: /Users/thomasvincent/Developer/github.com/Cacti/spine
# Build directory: /Users/thomasvincent/Developer/github.com/Cacti/spine/build-release
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(platform_env "/Users/thomasvincent/Developer/github.com/Cacti/spine/build-release/test_platform_env")
set_tests_properties(platform_env PROPERTIES  _BACKTRACE_TRIPLES "/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;692;add_test;/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;814;spine_add_platform_test;/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;0;")
add_test(platform_time "/Users/thomasvincent/Developer/github.com/Cacti/spine/build-release/test_platform_time")
set_tests_properties(platform_time PROPERTIES  _BACKTRACE_TRIPLES "/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;692;add_test;/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;814;spine_add_platform_test;/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;0;")
add_test(platform_process "/Users/thomasvincent/Developer/github.com/Cacti/spine/build-release/test_platform_process")
set_tests_properties(platform_process PROPERTIES  _BACKTRACE_TRIPLES "/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;692;add_test;/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;814;spine_add_platform_test;/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;0;")
add_test(platform_socket "/Users/thomasvincent/Developer/github.com/Cacti/spine/build-release/test_platform_socket")
set_tests_properties(platform_socket PROPERTIES  _BACKTRACE_TRIPLES "/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;692;add_test;/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;814;spine_add_platform_test;/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;0;")
add_test(platform_error "/Users/thomasvincent/Developer/github.com/Cacti/spine/build-release/test_platform_error")
set_tests_properties(platform_error PROPERTIES  _BACKTRACE_TRIPLES "/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;692;add_test;/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;814;spine_add_platform_test;/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;0;")
add_test(platform_fd "/Users/thomasvincent/Developer/github.com/Cacti/spine/build-release/test_platform_fd")
set_tests_properties(platform_fd PROPERTIES  _BACKTRACE_TRIPLES "/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;692;add_test;/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;814;spine_add_platform_test;/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;0;")
add_test(platform_dns "/Users/thomasvincent/Developer/github.com/Cacti/spine/build-release/test_platform_dns")
set_tests_properties(platform_dns PROPERTIES  _BACKTRACE_TRIPLES "/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;692;add_test;/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;814;spine_add_platform_test;/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;0;")
add_test(platform_thread_name "/Users/thomasvincent/Developer/github.com/Cacti/spine/build-release/test_platform_thread_name")
set_tests_properties(platform_thread_name PROPERTIES  _BACKTRACE_TRIPLES "/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;692;add_test;/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;814;spine_add_platform_test;/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;0;")
add_test(ping_reply_validation "/Users/thomasvincent/Developer/github.com/Cacti/spine/build-release/test_ping_reply_validation")
set_tests_properties(ping_reply_validation PROPERTIES  _BACKTRACE_TRIPLES "/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;830;add_test;/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;0;")
add_test(ping_ipv6_scope "/Users/thomasvincent/Developer/github.com/Cacti/spine/build-release/test_ping_ipv6_scope")
set_tests_properties(ping_ipv6_scope PROPERTIES  _BACKTRACE_TRIPLES "/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;845;add_test;/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;0;")
add_test(systemd_notify "/Users/thomasvincent/Developer/github.com/Cacti/spine/build-release/test_systemd_notify")
set_tests_properties(systemd_notify PROPERTIES  _BACKTRACE_TRIPLES "/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;870;add_test;/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;0;")
add_test(sandbox "/Users/thomasvincent/Developer/github.com/Cacti/spine/build-release/test_sandbox")
set_tests_properties(sandbox PROPERTIES  _BACKTRACE_TRIPLES "/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;898;add_test;/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;0;")
add_test(json_log "/Users/thomasvincent/Developer/github.com/Cacti/spine/build-release/test_json_log")
set_tests_properties(json_log PROPERTIES  _BACKTRACE_TRIPLES "/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;915;add_test;/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;0;")
add_test(env_scrub "/Users/thomasvincent/Developer/github.com/Cacti/spine/build-release/test_env_scrub")
set_tests_properties(env_scrub PROPERTIES  _BACKTRACE_TRIPLES "/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;963;add_test;/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;0;")
add_test(circuit_breaker "/Users/thomasvincent/Developer/github.com/Cacti/spine/build-release/test_circuit_breaker")
set_tests_properties(circuit_breaker PROPERTIES  _BACKTRACE_TRIPLES "/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;1001;add_test;/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;0;")
add_test(dump_config "/Users/thomasvincent/Developer/github.com/Cacti/spine/build-release/test_dump_config")
set_tests_properties(dump_config PROPERTIES  _BACKTRACE_TRIPLES "/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;1029;add_test;/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;0;")
add_test(check_mode "/Users/thomasvincent/Developer/github.com/Cacti/spine/build-release/test_check_mode")
set_tests_properties(check_mode PROPERTIES  TIMEOUT "30" _BACKTRACE_TRIPLES "/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;1057;add_test;/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;0;")
add_test(dry_run "/Users/thomasvincent/Developer/github.com/Cacti/spine/build-release/test_dry_run")
set_tests_properties(dry_run PROPERTIES  _BACKTRACE_TRIPLES "/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;1088;add_test;/Users/thomasvincent/Developer/github.com/Cacti/spine/CMakeLists.txt;0;")
