{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cacti-spine.serviceAccountName" . }}
  labels:
    {{- include "cacti-spine.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
