#!/usr/bin/env python3
"""Generate seed SQL for load testing spine with N devices.

Each device gets 5 poller_item rows (one per OID). Output is written to
stdout so the caller can redirect: gen-seed.py --count 500 > load-seed.sql
"""
import argparse
import sys


# OIDs polled per device, matching what gen-snmprec.py emits.
POLL_OIDS: list[tuple[str, str]] = [
    ("sysDescr",   "1.3.6.1.2.1.1.1.0"),
    ("sysObjID",   "1.3.6.1.2.1.1.2.0"),
    ("sysUpTime",  "1.3.6.1.2.1.1.3.0"),
    ("sysName",    "1.3.6.1.2.1.1.5.0"),
    ("ifNumber",   "1.3.6.1.2.1.2.1.0"),
]


def device_ip(n: int) -> str:
    if n <= 254:
        return f"192.0.2.{n}"
    offset = n - 254
    if offset > 254:
        raise ValueError(f"device {n} exceeds supported range (max 508)")
    return f"198.51.100.{offset}"


def emit(line: str = "") -> None:
    print(line)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--count",
        type=int,
        default=500,
        metavar="N",
        help="number of devices to seed (max 508, default: 500)",
    )
    parser.add_argument(
        "--snmp-community",
        default="public",
        metavar="STR",
        help="SNMP community string (default: public)",
    )
    parser.add_argument(
        "--snmp-version",
        type=int,
        choices=[1, 2],
        default=2,
        metavar="VER",
        help="SNMP version: 1 or 2 (default: 2)",
    )
    parser.add_argument(
        "--snmp-port",
        type=int,
        default=16100,
        metavar="PORT",
        help="SNMP UDP port snmpsim listens on (default: 16100)",
    )
    args = parser.parse_args()

    if args.count < 1 or args.count > 508:
        parser.error("--count must be between 1 and 508")

    community = args.snmp_community.replace("'", "''")
    version   = args.snmp_version
    port      = args.snmp_port

    emit("-- Load test seed SQL generated by gen-seed.py")
    emit(f"-- {args.count} devices x {len(POLL_OIDS)} OIDs = {args.count * len(POLL_OIDS)} poller_item rows")
    emit()

    # host table
    emit("CREATE TABLE IF NOT EXISTS `host` (")
    emit("  `id`               int(10) unsigned NOT NULL AUTO_INCREMENT,")
    emit("  `hostname`         varchar(250) NOT NULL DEFAULT '',")
    emit("  `snmp_community`   varchar(100) NOT NULL DEFAULT '',")
    emit("  `snmp_version`     tinyint(1) unsigned NOT NULL DEFAULT 1,")
    emit("  `snmp_port`        mediumint(5) unsigned NOT NULL DEFAULT 161,")
    emit("  `status`           tinyint(2) NOT NULL DEFAULT 0,")
    emit("  `disabled`         char(2) NOT NULL DEFAULT '',")
    emit("  PRIMARY KEY (`id`)")
    emit(") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;")
    emit()

    # poller_item table
    emit("CREATE TABLE IF NOT EXISTS `poller_item` (")
    emit("  `local_data_id`  mediumint(8) unsigned NOT NULL DEFAULT 0,")
    emit("  `host_id`        mediumint(8) unsigned NOT NULL DEFAULT 0,")
    emit("  `action`         tinyint(2) NOT NULL DEFAULT 1,")
    emit("  `hostname`       varchar(250) NOT NULL DEFAULT '',")
    emit("  `snmp_community` varchar(100) NOT NULL DEFAULT '',")
    emit("  `snmp_version`   tinyint(1) unsigned NOT NULL DEFAULT 1,")
    emit("  `snmp_port`      mediumint(5) unsigned NOT NULL DEFAULT 161,")
    emit("  `snmp_timeout`   int(10) unsigned NOT NULL DEFAULT 500,")
    emit("  `rrd_name`       varchar(19) NOT NULL DEFAULT '',")
    emit("  `rrd_path`       varchar(255) NOT NULL DEFAULT '',")
    emit("  `arg1`           text,")
    emit("  `arg2`           varchar(255) NOT NULL DEFAULT '',")
    emit("  `arg3`           varchar(255) NOT NULL DEFAULT '',")
    emit("  PRIMARY KEY (`local_data_id`, `rrd_name`)")
    emit(") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;")
    emit()

    # poller_output table (spine writes results here)
    emit("CREATE TABLE IF NOT EXISTS `poller_output` (")
    emit("  `local_data_id` mediumint(8) unsigned NOT NULL DEFAULT 0,")
    emit("  `rrd_name`      varchar(19) NOT NULL DEFAULT '',")
    emit("  `time`          datetime NOT NULL DEFAULT '0000-00-00 00:00:00',")
    emit("  `output`        text NOT NULL,")
    emit("  PRIMARY KEY (`local_data_id`, `rrd_name`, `time`)")
    emit(") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;")
    emit()

    # poller_time table (spine updates this on completion)
    emit("CREATE TABLE IF NOT EXISTS `poller_time` (")
    emit("  `poller_id` tinyint(3) unsigned NOT NULL DEFAULT 0,")
    emit("  `end_time`  timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP")
    emit(") ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;")
    emit()

    # host rows -- INSERT in batches of 100 to keep statement size manageable
    BATCH = 100
    host_rows: list[str] = []
    for n in range(1, args.count + 1):
        ip = device_ip(n)
        # status=3 (up), disabled='' (enabled)
        host_rows.append(
            f"  ({n}, '{ip}', '{community}', {version}, {port}, 3, '')"
        )

    for i in range(0, len(host_rows), BATCH):
        chunk = host_rows[i:i + BATCH]
        emit("INSERT INTO `host`")
        emit("  (`id`, `hostname`, `snmp_community`, `snmp_version`, `snmp_port`, `status`, `disabled`)")
        emit("VALUES")
        emit(",\n".join(chunk) + ";")
        emit()

    # poller_item rows
    item_rows: list[str] = []
    for n in range(1, args.count + 1):
        ip = device_ip(n)
        for oid_idx, (rrd_name, oid) in enumerate(POLL_OIDS):
            # local_data_id: unique per (device, oid) -- simple linear encoding
            local_data_id = (n - 1) * len(POLL_OIDS) + oid_idx + 1
            rrd_path = f"/var/lib/cacti/rrd/{n}/ds_{oid_idx + 1}.rrd"
            item_rows.append(
                f"  ({local_data_id}, {n}, 1, '{ip}', '{community}', "
                f"{version}, {port}, 500, '{rrd_name}', '{rrd_path}', '{oid}', '', '')"
            )

    for i in range(0, len(item_rows), BATCH):
        chunk = item_rows[i:i + BATCH]
        emit("INSERT INTO `poller_item`")
        emit(
            "  (`local_data_id`, `host_id`, `action`, `hostname`, `snmp_community`,"
        )
        emit(
            "   `snmp_version`, `snmp_port`, `snmp_timeout`, `rrd_name`, `rrd_path`, `arg1`, `arg2`, `arg3`)"
        )
        emit("VALUES")
        emit(",\n".join(chunk) + ";")
        emit()


if __name__ == "__main__":
    main()
